version: '2.1'

services:
    mariadb:
        image: docker.io/bitnami/mariadb:10.5
        ports:
            - '3306:3306'
        volumes:
            - 'mariadb_data:/bitnami/mariadb'
        environment:
            MARIADB_DATABASE:
            MARIADB_ROOT_USER:
            MARIADB_ROOT_PASSWORD:
        healthcheck:
            test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
            interval: 15s
            timeout: 5s
            retries: 6

volumes:
    mariadb_data:
        driver: local

networks:
    bubble:
        external: true
