server:
    port: 8085

spring:
    datasource:
        url: ${MARIADB_URL}
        username: ${MARIADB_USERNAME}
        password: ${MARIADB_PASSWORD}
        tomcat:
            test-while-idle: true
            validation-query: SELECT 1
        hikari:
            driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
